### ISSUE TITLE
brower_verify.lua中的cookies的验证问题

### ISSUE THREAD

**Issue by spoock1024** [alexazhou/VeryNginx#102]
在**verify_cookie()**中，使用了`ngx.header["Set-Cookie"] =  cookie_prefix .. "_sign_cookie=" .. sign .. '; path=/' `这样的语句，通过这样的语句会将之前的请求cookies中的值会覆盖吗？

**Comment by alexazhou** [comment]
不会吧，**set-cookie** 头是只会从服务器发送给客户端的，用来设置客户端的 cookie，并不会对客户端其他 cookie 产生影响

除非 cookie 命名重复的情况下，不过命名的问题可以通过 cookie_prefix 来解决

**Comment by spoock1024** [comment]
嗯，这个问题我自己也刚刚测试了，通过`ngx.header["Set-Cookie"]`是直接在后面添加的，没有问题。
