### ISSUE TITLE
设置的规则不生效

### ISSUE THREAD

**Issue by nosun** [alexazhou/VeryNginx#103]
之前用过 openresty， 安装 verynginx 的时候直接只装了 verynginx 部分，可以正常运行，测试了一下默认的 filter 规则， 比如防止 scan git 的，都是正常运行的。

增加一些自己的规则，比如防止某个 ip 访问，比如 设置 访问频次 100 秒钟内 只能访问 3次， 比如 所有的request， 全部返回 403 类似的，这些都无法生效。

是什么问题呢？

**Comment by alexazhou** [comment]
请给出一个最小的可以重现的方法，我来排查

**Comment by nosun** [comment]
您能否加一下我的qq 917670021

**Comment by alexazhou** [comment]
还是直接在 Github 上面提交吧，因为精力的原因，没办法提供一对一的技术支持

**Comment by nosun** [comment]
明白， 我 通过 client ip 设置 了一个 ip ， 这个ip 我通过 nginx 日志 可以看到，也就是我自己的ip地址，这个是 matcher 规则，然后我 增加了一个 filter 规则， 也就是匹配到这个ip 执行 block 规则， 返回 403.
设置好之后，我去访问网址，发现还可以访问，并没有返回  403

**Comment by nosun** [comment]
关于 限速这块， 同样的，我直接增加 限速的规则， Request count 设置 3， 时间设置 100， 然后 return 403. 并没有返回预期的结果。

**Comment by nosun** [comment]
https://www.doriswedding.com/vn/index.html#

**Comment by nosun** [comment]
这个是网址， 都是默认的密码

**Comment by nosun** [comment]
又或者，如果我把localhost 这条规则，匹配到 所有页面， block掉，是不是应该在本地测试的时候，逗返回 403.理论上应该是这样的，但是我这边在本地测试的时候，没有效果，也很奇怪。

我觉得应该是某个地方没有弄对。

**Comment by nosun** [comment]
我的这台 nginx 是台 proxy， 和这个有关系么？

**Comment by alexazhou** [comment]
我觉得最基本的 ip 匹配这一块，肯定是没问题的，应该还是安装／配置的原因。

或者如果如果可以给我提供一个可以重现的最小例子，我可以帮你找到原因

**Comment by nosun** [comment]
我说一下安装流程， openresty 是以前安装好的，1.11.2.1， verynginx 是 master 分支上的， 按照说明的要求， 仅仅 把三个 include 语句 插入相对应的点。 没有感觉特别出入的地方。

**Comment by nosun** [comment]
最简单的例子，就是把自己 ban 掉，所有的请求返回 403， 这个在我本地也没成功。

**Comment by nosun** [comment]
会不会是权限问题， 后台无法写入这些新的规则

**Comment by alexazhou** [comment]
退出再重新登录，然后看新添加的配置在不在，就可以确认是否保存了

**Comment by nosun** [comment]
不在

**Comment by nosun** [comment]
这些规则怎么保存的？ 需要怎样才能写入呢？

**Comment by nosun** [comment]
明白了，每次修改规则，在底部有个弹出框，我这边没有点击 save……

**Comment by alexazhou** [comment]
😓原来是这样。我去补一下文档吧
