### ISSUE TITLE
proxy_pass gogs 403 errer

### ISSUE THREAD

**Issue by jim3ma** [alexazhou/VeryNginx#107]
运行gogs 后，nginx反代gogs，配置了VeryNginx以后，`https://gogs/user/repo.git`这样所有带`.git`结尾的链接都被导向403了，注释掉`include /opt/verynginx/verynginx/nginx_conf/in_http_block.conf;`后正常，但VeryNginx就没法使用了，稍候会给出详细的复现步骤哈。

**Comment by alexazhou** [comment]
这是 VeryNginx 默认有一条规则阻止 .git 这样路径的文件，把那个 matcher 修改掉就好啦

发自我的 iPhone
