### ISSUE TITLE
Translate to english?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [alexazhou/VeryNginx#11]
Your project looks really nice, although I must admit that I don't speak your language :)

Is it possible to have it at least in English?

**Comment by alexazhou** [comment]
yes, english support will be added later

**Comment by julianxhokaxhiu** [comment]
thanks!

**Comment by kkas** [comment]
+1

**Comment by alexazhou** [comment]
English version is coming

**Comment by alexazhou** [comment]
The verynginx dashboard is in english now.

Remaining a few documents in Chinese, the translation will coming soon

**Comment by julianxhokaxhiu** [comment]
Thanks!

**Comment by alexazhou** [comment]
Document in english was ready!
