### ISSUE TITLE
In init phase, Load config file from disk? 

### ISSUE THREAD

**Issue by fankeke** [alexazhou/VeryNginx#113]
init_by_lua_file    ./verynginx/lua_script/on_init.lua;

`load_from_file` will be issued,  but you seems did not give a example of   'configs/config.json'. 

 so I wonder What will happend in init phase and how this happend ?  

ALSO, I notice  you put `load_from_file` in rewrite phase(because you called  load_from_file in VeryNginxConfig.lua and required this module in on_rewrite)   and it will block nginx eventloop  because of  `io.open & io.read` API . 

many thanks!

**Comment by alexazhou** [comment]
1, You are right, the file 'configs/config.json' was not existed at default. You need to access the dashboard, and save config at least once, the config.json will auto generated.

2, The ``load_from_file`` method will consume some cpu time ，but it not exec at every request，it was only run once at boot time, or the config.json has changed. So don't warry about it may block nginx eventloop :-P

**Comment by fankeke** [comment]
thanks for your reply :)

1, I run VN in my pc and accessed to dashboard and try to do some config things, but not `config.json` file generated in ｀config/config.json` , any notice I missed ？ maybe I will refer to your wiki later.    

2  yes, only at boot time or config.json file altered then  the `load_from_file` will run.  
  previously I turn off the lua_code_cache and every request will have it's own VM ,so ..... 

3 again, Thanks for your reply and your awesome work，I will learn something from It .  maybe some 'hot lua code' loaded  method    :)

**Comment by alexazhou** [comment]
This Is my pleasure .

Specifically, when you modify some of the configuration above the panel, you will see a toolbar at the bottom, there is a save button, click on the button will generate ``config.json``.

If the ``config.json`` not found, may be you can try:

```
chmod -R 777 /opt/verynginx/verynginx/config
```
