### ISSUE TITLE
使用自己编译的openresty修改配置出错

### ISSUE THREAD

**Issue by imzye** [alexazhou/VeryNginx#116]
您好，我的机器上自带了openresty，我直接执行的
python install.py install verynginx
安装的verynginx
修改Nginx配置加入in_http_block.conf的时候出现问题，

nginx: [emerg] unknown directive "balancer_by_lua_file" in /opt/verynginx/verynginx/nginx_conf/in_http_block.conf:3
nginx: configuration file /etc/openresty/openresty.conf test failed

麻烦帮忙看一下，是什么原因？

**Comment by alexazhou** [comment]
应该是自带的 OpenResty 库没有包含 balancer_by_lua_file，安装新版本的 OR 就可以了

参考 ＃108

**Comment by imzye** [comment]
谢谢！

**Comment by JoyChou93** [comment]
hi,imzye:
    这个问题最后怎么解决的

**Comment by Castleeee** [comment]
我安装了OR还时出现这个错误，请问是怎么解决的
