### ISSUE TITLE
能不能不要用/opt/verynginx/verynginx这样的绝对路径？

### ISSUE THREAD

**Issue by ladygh** [alexazhou/VeryNginx#118]
如题，
比如FreeBSD压根没有opt这样的目录，而linux也不是每个发行版都把nginx装到同样的路径下的
建议全部修改为相对路径啊。

**Comment by alexazhou** [comment]
没有这个目录手动建立就好啦。

这也是权衡过的，之前的版本没有固定安装目录，大家的使用过程中产生了很多问题…

发自我的 iPhone

**Comment by ladygh** [comment]
我觉得不如引入一个setting来设置目录位置，然后其余地方全部用变量实现了。。

**Comment by alexazhou** [comment]
这样需要动态替换nginx配置文件中的配置路径，技术上实现不优雅。

主要是可变路径会带来使用和维护上的很多问题，却对应的优势却不明显。所以我不倾向这么做

发自我的 iPhone

**Comment by ladygh** [comment]
试了下只需要把verynginx\nginx_conf 里的文件里的所有/opt/verynginx/verynginx/替换成了/usr/local/etc/nginx/verynginx/就好了，
等我测试下有没有啥问题

**Comment by ladygh** [comment]
一个问题，对于网站，没有办法可以用独立的server来跑verynginx
比如说我主站用www.test.com，我不想让verynginx跑在www下，毕竟容易被人发现路径，可不可以搞个域名比如verynginx.test.com来运行verynginx，但是管理的是www.test.com？

**Comment by alexazhou** [comment]
这几个文件是 VeryNginx 的组成部分，可能随着后续升级发生变化，修改了这个升级就有困难了

发自我的 iPhone

**Comment by ladygh** [comment]
汇报一个问题，summary 页面没有限制显示的条数
这就导致了对于访问量大的站点，访问summary因为数据量太大，会直接导致浏览器高cpu占用从而卡死
