### ISSUE TITLE
运行python install.py install出现如下错误然后停止了

### ISSUE THREAD

**Issue by coldwinds** [alexazhou/VeryNginx#139]
用的版本是VeryNginx-0.3.3

[root@vps VeryNginx-0.3.3]# python install.py install
### makesure the work directory is clean
rm -rf openresty-1.9.15.1
Traceback (most recent call last):
  File "install.py", line 131, in <module>
    install_openresty()
  File "install.py", line 34, in install_openresty
    ans = common_input(' Found %s in current directory, use it?(y/n)'%openresty_pkg)
  File "install.py", line 98, in common_input
    if sys.version_info.major == 3:
AttributeError: 'tuple' object has no attribute 'major'

**Comment by coldwinds** [comment]
python --version
Python 2.6.6

因为这个造成的

sys.version_info

    A tuple containing the five components of the version number: major, minor, micro, releaselevel, and serial. All values except releaselevel are integers; the release level is 'alpha', 'beta', 'candidate', or 'final'. The version_info value corresponding to the Python version 2.0 is (2, 0, 0, 'final', 0). The components can also be accessed by name, so **sys.version_info[0] is equivalent to sys.version_info.major** and so on.

    New in version 2.0.

    **Changed in version 2.7: Added named component attributes**

https://docs.python.org/2/library/sys.html

**Comment by alexazhou** [comment]
多谢你的提交，已经合并 PR 了
