### ISSUE TITLE
ngx_openresty-1.x.x.x.tar.gz to openresty-1.9.7.3.tar.gz

### ISSUE THREAD

**Issue by warmchang** [alexazhou/VeryNginx#14]
Hi,

I found that the software openresty updated to version 1.9.7.3, and the filename has been changed to openresty-1.9.7.3.tar.gz from ngx_openresty-1.x.x.x.tar.gz.

Pls modify the chapters "安装 Nginx / OpenResty" in file readme.md.

**Comment by alexazhou** [comment]
Thanks , i have already add a description for OpenResty version in readme.md . 
But  i didn't change the openresty download address immediately, because i don't know why the format of address has changed. Maybe is not a stable version . 

So that's keep it whit some description

**Comment by warmchang** [comment]
ok. :-)
