### ISSUE TITLE
能用来防CC么

### ISSUE THREAD

**Issue by liwanglin12** [alexazhou/VeryNginx#15]

**Comment by alexazhou** [comment]
目前还没有这个功能，但是防CC在开发计划中，所以后面的版本会有

**Comment by liwanglin12** [comment]
←_←说起来这个要升级要怎么升。。

**Comment by alexazhou** [comment]
替换VeryNginx文件夹就可以啦
ps: 如果新版本配置格式有变化的话还需要删除config.json并重新配置

**Comment by liwanglin12** [comment]
谢谢喽，正在尝试用nginx加模块编译

**Comment by fanchangyong** [comment]
请问这个功能大概什么时候会出？另外，可否大体介绍一下思路？最近在做相关的工作，想了解一下，谢谢！

**Comment by alexazhou** [comment]
目前提供了

* Browser Verify **浏览器验证**
* Frequency Limit  **访问频率限制**

这两个模块，来实现一些防 CC 的功能。
