### ISSUE TITLE
求一个自动识别攻击ip的策略

### ISSUE THREAD

**Issue by hu9msbedu** [alexazhou/VeryNginx#17]
简单粗暴的办法就是：
当一个ip请求超过300，自动判断判断为攻击ip，加入防火墙。

**Comment by alexazhou** [comment]
这个太简单粗暴了😓，在有些情况下可能会引起异常...
我正在设计一个可配置的防CC模块，后续(这一两周)会加入进来

**Comment by liwanglin12** [comment]
已经提过了233

**Comment by alexazhou** [comment]
已经加入请求频率限制功能。

虽然不是完全意义上的自动识别攻击IP，但是也可以起到一定的防CC攻击的效果。

剩下的后面再改进吧。
