### ISSUE TITLE
配置无法保存

### ISSUE THREAD

**Issue by Airsola** [alexazhou/VeryNginx#186]
已按照故障手册进行了操作

1，未点击保存按钮

修改配置后，页面底部会出现一个浮动条，提示保存，在点击浮动条上的保存按钮之后，配置才会进行写入
2, nginx 进程对 /opt/verynginx/verynginx/configs/ 无写权限

执行 chmod -R 777 /opt/verynginx/verynginx/configs
3, nginx 设置的 client body 太小，导致请求体被缓存到文件，导致 lua 代码没有获取到请求体，保存时会提示请求失败

在nginx.conf中增加一句，client_body_buffer_size 128k;

但是仍然发现配置无法保存

安装方式是  python install.py install

nginx.conf 中的  client_body_buffer_size 128k; 这个配置 具体是放在哪个位置呢？放在 server 里面好像没有生效

**Comment by JoyChou93** [comment]
```
Syntax: | client_body_buffer_size size;
-- | --
client_body_buffer_size 8k\|16k;
http, server, location
```

一般放在http。

**Comment by Airsola** [comment]
@JoyChou93  thx~ 
问题解决了  发现原因是 nginx.conf 中写的  user  nobody; 这种配置好像无法保存文件，即使权限已经是777.这点可以补充到 Trouble Shooting 中么，方便后续童鞋绕过坑

**Comment by alexazhou** [comment]
@JoyChou93  @Airsola 

感谢二位。
已经补充到了 Trouble Shooting 中。
