### ISSUE TITLE
咨询负载均衡的问题

### ISSUE THREAD

**Issue by alswl** [alexazhou/VeryNginx#202]
我看了 `lua_script/module/backend_proxy.lua` 的代码，发现里面做的逻辑是根据 ip hash 和 weight 进行负载均衡，没有 Upstream max_fails / fails_timeout 等设定。

这是否意味着 VeryNginx 配置的 Backend 不支持这些 FailOver 的配置？

如果我的理解有误，请给予指导。

**Comment by JoyChou93** [comment]
是的，不支持。不过你可以手动在conf里配置，

**Comment by alswl** [comment]
@JoyChou93 我想动态调整 Upstream 内节点，甚至是管理 Upstream 本身（增减调整 Upstream）。
