### ISSUE TITLE
求加一个301的，谢谢爱你么么哒。

### ISSUE THREAD

**Issue by hu9msbedu** [alexazhou/VeryNginx#22]
301到一个url谢谢啦。

**Comment by alexazhou** [comment]
具体是怎样的使用场景呢，可否详细描述一下？

目前Custom Action中的Redirect功能可以对请求进行重定向，这个功能使用的是302，不知道这个功能能不能满足你的需求

**Comment by hu9msbedu** [comment]
`113.138.236.151 - - [04/Mar/2016:15:01:57 +0800] "GET /tg/ HTTP/1.1" 500 600 "http://hui.scjnjp.com" "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0; MyIE 3.01)Cache-Control: no-store, must-revalidate"
以上是我今天收到的攻击。
就是UA判断是  must-revalidate 有403 ，500，没有310 可以设置到 301 到www.gogole.com 就好了。

**Comment by alexazhou** [comment]
遇到这种攻击推荐使用Filter来block，或者使用browser verify都可以

具体方法是：
1，先定义一个Matcher，里面添加UserAgent作为条件
2，在Filter中添加规则，选择刚才添加的Matcher，选择block（如果想使用301而不是block的话可以在redirect中配置，方法是一样的）

**Comment by hu9msbedu** [comment]
谢谢。@alexazhou 
https://drive.google.com/open?id=0B0GRom_D-MgXOHJla080T2JXdE0
正在被攻击。

**Comment by alexazhou** [comment]
看不到链接里面的文件，不知道你弄好了没有😓
如果还有问题直接给我发邮件吧 AlexaZhou@163.com

**Comment by hu9msbedu** [comment]
hi .现在又来攻击了...

**Comment by hu9msbedu** [comment]
能提一个建议不。对于这样的攻击 只要机器不被拉入黑洞，对于这样的攻击特征，写入iptables或者ufw，直接拒绝，会不会好一点？
