### ISSUE TITLE
无法正则匹配问号?的链接

### ISSUE THREAD

**Issue by meilele** [alexazhou/VeryNginx#226]
无法正则匹配问号?的链接。
比如我要匹配/index.php?id=3
用\转义字符不得行，nginx官方说要匹配问号要用if才行。后台面板无法使用IF

**Comment by alexazhou** [comment]
现在还不能直接匹配问号，我理解你是想匹配参数，也就是包含参数的请求，这种情况可以创建一个 matcher，里面参数用正则表达式匹配 * ，这样应该可以。

**Comment by sisiww** [comment]
> 现在还不能直接匹配问号，我理解你是想匹配参数，也就是包含参数的请求，这种情况可以创建一个matcher，里面参数用正则表达式匹配*，这样应该可以。

/index.php?id=3 我需要匹配这样的绝对链接，包括？后面的参考也要传递。可不可以直接在config.json这个文件里面直接设置呢？

**Comment by sisiww** [comment]
具体匹配链接是   /search?(.*)  然后控制单子个IP在一定时间内访问这个链接的频率。
