### ISSUE TITLE
VeryNginx 后端Lua数据采集和前端JS界面显示的数据交互

### ISSUE THREAD

**Issue by yashun** [alexazhou/VeryNginx#29]
您好，我想请问作者的是关于VeryNginx 后端Lua数据采集和前端JS界面显示的数据交互是如何实现的？JS是怎么样读取lua采集到的数据的，对性能有没有影响，我最近也在开发这个东西，但是是刚入门，懂得不是很多，求赐教，也可发邮件到我的信箱Email：yashun.ren@gmail.com，感谢您的指导~

**Comment by alexazhou** [comment]
VeryNginx的前端是一个静态页面，在打开面板的时候就一次加载完成了。然后在操作的时候通过Ajax请求和后端的数据接口进行交互。具体你可以打开浏览器的 web检查器-> 网络， 在那一栏中可以看到数据交互的过程。 

大概就是这样，你可以一边进行操作，一边观察网络请求，这样很快就可以明白啦

**Comment by yashun** [comment]
那请问后端的数据接口与Ajax是通过什么方式来进行数据传递的，是以文件方式，还是其他什么方式？原谅我不懂前端开发，感谢您的指导

**Comment by alexazhou** [comment]
呃，Ajax是网络请求的一种，也是一种很通用的技术，这里传输的是json格式的数据

建议你把相关的基础知识补一补，然后就明白啦

**Comment by yashun** [comment]
好的，谢谢啦，我已经看到两个是通过json数据进行的数据交互，谢谢你了
