### ISSUE TITLE
几个安全问题

### ISSUE THREAD

**Issue by DeepSkyFire** [alexazhou/VeryNginx#34]
VeryNginx做的很不错，必须赞。但还是有些安全问题。

管理面板的地址，在nginx的反代模式下能直接使用www.xxx.com(反代的域名)/verynginx/index.html直接访问到Verynginx的管理面板，这其实是很不安全的。而且我尝试了各种各样的改法都无法修正这问题。

在cookies的验证里 会出现verynginx字段，这类名字会成为一个强特征，让人有针对的地方。

建议能在这两个问题上有自主修改的空间。还是非常感谢作者。

**Comment by alexazhou** [comment]
非常感谢你的提醒，目前使用固定的管理入口地址，以及cookies字段名确实不太好，我打算在 VeryNginx 接下来的版本中加入自定义管理入口，和 cookies 字段名这样的功能，这样应该可以消除这个隐患。

这个 Issue 先保留着，我会在完成这部分代码之后，再关掉它

另外如果你在目前的使用中需要修改控制面板的入口，也可以通过配置一些规则达到目的，参考
https://github.com/alexazhou/VeryNginx/issues/27

**Comment by DeepSkyFire** [comment]
因为我的Verynginx是放置在前端反代服务器上的，主要比较头疼的问题还是我访问我反代的域名+管理面板的绝对路径也能进入管理面板，我在Matcher里已经加了一条Host = xxx.xxx.xxx.xxx URI ≈ ^/vn的规则但是也无法解决这个问题。不知如何才能限制只允许从IP访问管理面板而反代的域名无法访问？还请作者帮忙下。。

**Comment by alexazhou** [comment]
可以定义一个
Matcher： Host != xxx.xxx.xxx.xxx, URI ≈ ^/verynginx 

然后在Filter中把这个 Matcher 给 block 掉，应该就可以屏蔽掉了非ip方式的访问了

**Comment by DeepSkyFire** [comment]
感謝作者！已經成功的屏蔽了域名訪問控制面板

**Comment by alexazhou** [comment]
🍻，太客气啦～

另外对 VeryNginx 有什么想法，或者使用中有什么问题，都欢迎向我提出来。

**Comment by DeepSkyFire** [comment]
Re:

在实际使用的时候我发现内置的attack_backup_0与attack_code_0这两个规则都无法正常拦截

**Comment by alexazhou** [comment]
我还没有看懂你指出来规则里少了的东西是什么，能不能说详细一点

这两条规则如果启用了的话，你可以试试访问 
/back.sql
/.git/aaa

这些应该都会被屏蔽掉

**Comment by DeepSkyFire** [comment]
attack_backup_0的URI ≈ .(haccess|bash_history|ssh|sql)$ 這個無法屏蔽下載.htaccess文件。。因為內置規則裏漏了個t。。
URI ≈ .(htaccess|bash_history|ssh|sql)$ 加上之後才能正常屏蔽。。

**Comment by alexazhou** [comment]
😰，看到了，我去修正它

多谢

**Comment by alexazhou** [comment]
在 6f46855 加入了可以自定义控制面板入口的功能

**Comment by galenzhao** [comment]
还希望添加IP获取来源自定义header

**Comment by alexazhou** [comment]
@galenzhao  我还不是很明白，你是说在自定义 Header 中获取源 IP 吗

**Comment by galenzhao** [comment]
是的 ，哈哈 汉语不太好

**Comment by DeepSkyFire** [comment]
其实楼上的只是想表达说获取header中的源IP，因为用CDN的话设置IP白名单的功能就基本上无用了。

**Comment by alexazhou** [comment]
在 5bf8cf7 中已经完成了可以设置 cookies 前缀的功能，应该算是解决了这个问题。

 几天内即会合并到master。
