### ISSUE TITLE
能否加入缓存功能？

### ISSUE THREAD

**Issue by m1911** [alexazhou/VeryNginx#35]
加入缓存功能 这样就比较完美了

还有就是sql 防护规则可以自定义吗？

**Comment by alexazhou** [comment]
多谢提醒，这里的缓存功能具体是指什么样子的呢？

另外SQL防护规则可以自己定义的，根据需要添加适当的 Matcher 即可

**Comment by m1911** [comment]
http://www.osyunwei.com/?p=2084 可以看下这个文章 
你这sql 注入防的是get 和post的？

**Comment by alexazhou** [comment]
对，在 Post 和 Get 的时候都会进行过滤

这个功能我大概知道，因为这个功能可以通过 Nginx 配置文件的方式实现（ VeryNginx 是 Nginx 上的一个增强模块，不会影响到 Nginx 自己的功能），所以目前就不打算做到 VeryNginx 里面了

**Comment by m1911** [comment]
额  我知道可以通过配置文件。 就是感觉能在 web上面配置比较方便 也就这么一说

貌似现在好多waf 放不了cookie 的注入。 云锁也是这样

**Comment by m1911** [comment]
对了 现在你这个是单节点的 有考虑过多节点吗？

**Comment by alexazhou** [comment]
我觉得 cookie 注入的防御有一定困难，而且用到的地方也并不是特别多，所以放在后面考虑

你说的多接点是否指在多个机器上部署，然后统一通过一个面板进行管理吗？

如果是这样的情况，那还没有考虑，目前的打算是先把单节点做完善了，然后再扩展到其它

**Comment by m1911** [comment]
额 就是指统一管理
dashboard  lua_script  support 这三个目录 这个dashboard是面板管理 放在任意地方都可以吧？
 lua_script  support  这两个lua 的配置 只要nginx 能读取加载就行了吧？

**Comment by m1911** [comment]
nginx.conf 里面那段 代码只要放在nginx.conf 这个配置文件里面 然后所有虚拟机都会生效防御？

**Comment by alexazhou** [comment]
1，建议参考安装说明进行安装，因为VeryNginx 文件夹是一个整体，如果把 dashboard 位置改动了，就没办法工作了。。。

2，对所有的虚拟机都会生效

**Comment by m1911** [comment]
1、刚开始没仔细看文件 刚才仔细看了下 知道了配置文件放哪了
2、VeryNginxConfig.lua 这个貌似是面板的配置文件？ 如果是 我觉得还是吧面板和 模块的配置文件分开来 这样 面板就可以随便安装 这样是不是比现在这样方便？

**Comment by alexazhou** [comment]
VeryNginxConfig.lua 那个并不是配置文件，是负责生成配置文件的代码，配置会保存到 VeryNginx 目录下一个 config.json 文件中，所以配置文件本来就是独立出来的

**Comment by m1911** [comment]
大致了解 怎么搞了
登陆 提示Ajax request failed [status code = 404] 这什么情况？

**Comment by alexazhou** [comment]
可能是安装不对，建议仔细阅读安装说明，一般来说按照安装说明安装都是可以正常使用的

抱歉我没办法提供一对一的技术支持服务

**Comment by m1911** [comment]
我只是把/opt/VeryNginx 改成了自己的目录而已。

**Comment by alexazhou** [comment]
如果修改 /opt/VeryNginx 为其它目录，也是可以的，但是需要同步修改很多地方的代码，这样才能正常工作。

建议除非你知道怎么修改，不然不要修改这个地方，完全没有必要

**Comment by m1911** [comment]
#-----------------VeryNginx config code------------------
lua_package_path '/opt/VeryNginx/VeryNginx/lua_script/?.lua;;/opt/VeryNginx/VeryNginx/lua_script/module/?.lua;;';
lua_package_cpath '/opt/VeryNginx/VeryNginx/lua_script/?.so;;';
lua_code_cache on;

lua_shared_dict status 1m;
lua_shared_dict summary_long 10m;
lua_shared_dict summary_short 10m;

init_by_lua_file /opt/VeryNginx/VeryNginx/lua_script/on_init.lua;
rewrite_by_lua_file /opt/VeryNginx/VeryNginx/lua_script/on_rewrite.lua;
access_by_lua_file /opt/VeryNginx/VeryNginx/lua_script/on_access.lua;
log_by_lua_file /opt/VeryNginx/VeryNginx/lua_script/on_log.lua;
#---------------VeryNginx config code end-----------------

就是修改这段代码的目录 我知道 的 但是这段代码和登陆没什么相干吧

**Comment by alexazhou** [comment]
呃，这里肯定是需要修改的。主要是，其它代码中还有没有，我一下也想不起来了。。。

我也并没有测试过其它目录下的可用性

**Comment by m1911** [comment]
不会把目录写死了吧 这要写死那就。。。

**Comment by m1911** [comment]
搭建ok 了果然改目录不行 你这个要直接放在根目录
我弄的是绑定域名从新搞个虚拟机跑的。。
