### ISSUE TITLE
注入规则有问题

### ISSUE THREAD

**Issue by m1911** [alexazhou/VeryNginx#36]
添加防注入 and 1=1 和and 1=2 这种规则 立马500

**Comment by alexazhou** [comment]
我没有太明白，能否具体描述一下呢？
我这里好复线进行改进

**Comment by m1911** [comment]
http://i4.piimg.com/4b2a751b40c24992.png
上面的图片是在Matcher里面添加了个sql注入的规则
http://i4.piimg.com/4b2a751b40c24992.png
这张是在Filter里面添加的规则

这样就是一个放sql get注入的 但是这个规则配置保存了 测试的时候nginx 就报错500 了
http://t.70sec.net/Production/PRODUCT_DETAIL.asp?id=1513 
500错误

**Comment by alexazhou** [comment]
最上面两张图片都是 Filter 的，能放一张图，让我看看 Matcher 定义的怎样的吗。

初步认为500错误是内部匹配Matcher的时候出错了

**Comment by m1911** [comment]
http://i4.piimg.com/149b213c5de0067e.png  失误贴错图片了

**Comment by alexazhou** [comment]
我测试了图中的配置，但是并没有重现500的问题，😓

你确定是这条规则引起的么？可以的话能不能把/opt/verynginx/config.json 这个文件发给我，我看看有没有其它的异常

我的邮箱是 alexazhou@163.com

谢谢的你的反馈

**Comment by m1911** [comment]
已经发送给你了

**Comment by alexazhou** [comment]
多谢，我已经用你的config.json复现了500的情况，但还不知道问题在哪儿

预计今天应该可以修复好

**Comment by m1911** [comment]
看云锁的waf 插件说nginx 原生不支持post过滤  不知道你这个支持吗？

修复了我在测试下看看其他规则会不会在报错

**Comment by alexazhou** [comment]
可以支持 Post 参数过滤

500问题已经修复了，是代码中有个bug。。。
多谢你的反馈

**Comment by m1911** [comment]
500 我测试了情况是没有了 
想问下Filter返回的状态可以设计成自定义页面？

**Comment by alexazhou** [comment]
目前还没有支持返回自定义页面，后面版本考虑给加上

**Comment by m1911** [comment]
我想知道这个是怎么匹配关键字的
比如我过滤sql注入and 这个关键字是整个url 里面含有url 都会阻断还是怎么的？
例如http://www.baidu.com/andnews.php?id=1 这样 这个url 里面含有and 会被阻断吗？

**Comment by alexazhou** [comment]
匹配关键字的时候，是把每个参数和对应的值取出来作匹配的，在你举的例子中并不会误匹配url中的and

详见https://github.com/alexazhou/VeryNginx/wiki/Matcher

**Comment by m1911** [comment]
那就是只要设置好了关键字不管注入语句怎么改变都无所谓了？
/*|and|*/ 就算这样的 也会无法执行的是吧

**Comment by alexazhou** [comment]
应该是只要正则表达式能命中就可以

**Comment by m1911** [comment]
想问下 防CC 主要 怎么配置？

**Comment by alexazhou** [comment]
不太确定你说的防CC是指哪方面？

现在可以通过配置一些 Mather 来匹配 CC 流量的特征，然后用 Filter 进行 block

如果需要限制指定时间里面的请求数量的时候，还需要在 Nginx 配置里面来完成

**Comment by m1911** [comment]
指的是CC攻击流量防御配置

**Comment by m1911** [comment]
保存配置 报Ajax request failed [Network error]  这个错误是怎么回事？

**Comment by alexazhou** [comment]
表示网络请求失败，可能是网络问题，也可能是配置了某些规则阻止了自己的访问

**Comment by m1911** [comment]
Args ≈ (FromBase64String|z1) 貌似就是这个  这是防御菜刀连接的 难道你的程序也用到了这些？

**Comment by alexazhou** [comment]
post 配置时是通过 base64 编码的，应该是被误伤了

**Comment by m1911** [comment]
。。看来防护菜刀连接 得用其他关键字了

**Comment by alexazhou** [comment]
filter 那里规则是一条条匹配的，就像 iptables 一样，只使用匹配到的第一条规则

你可以先定义一条 accetp 规则，匹配上 verynginx 自己，放在最前面，这样就后面匹配啥就都可以了

**Comment by m1911** [comment]
测试了下 是可以拦截了 也不会耽误verynginx
