### ISSUE TITLE
这个能防护xss吗

### ISSUE THREAD

**Issue by m1911** [alexazhou/VeryNginx#37]
这个能防护xss插入吗

**Comment by alexazhou** [comment]
目前还不可以

**Comment by m1911** [comment]
看了你新改的程序配置 in_http_block.conf这个文件里面配置文件加载目录都指定死了 这样好吗？

**Comment by alexazhou** [comment]
其实任何一种设计肯定是有好处也有坏处，我也是权衡了多种可能的方式才设计成这样的。

通过 include 的方式把配置抽取出来，可以简化 nginx.conf ，并且为将来升级留下空间。 in_http_block.conf 里面写入固定的路径，其实只要 VeryNginx 本身安装在固定的路径就没问题（nginx路径可以任意）。我认为总的来说还比较好的。

**Comment by alexazhou** [comment]
当然如果你有更好的想法，也欢迎提出来

**Comment by m1911** [comment]
你这个需要加载的lua 这个配置文件和面板能分开不 我上次也提到过的 这样分开比较好的 分开了直接把lua 的配置文件放到nginx 安装目录conf 下面这样include包含方便路径就更固定了

**Comment by alexazhou** [comment]
这些本来是一个软件中的不同部分，分开之后，配置安装的复杂性会上升，而且后面的更新也是个问题。 

就没办法做到现在这样通过脚本自动更新了，所以分开肯定不好
