### ISSUE TITLE
Extract default VeryNginx configuration

### ISSUE THREAD

**Issue by legendecas** [alexazhou/VeryNginx#4]
What about extracting default VeryNginx configuration from nginx.conf into a file alone then includes it from nginx.conf by default?
If there is any update to this configuration in the future, upgrading will be simpler.

**Comment by alexazhou** [comment]
good idea !
In fact put VeryNginx  configuration to a alone file has more advantage
I will do that later

**Comment by alexazhou** [comment]
Fixed in 1a2609e
