### ISSUE TITLE
无法保存配置

### ISSUE THREAD

**Issue by liwanglin12** [alexazhou/VeryNginx#43]
Ajax request failed [status code = 200]……
虽然微信告诉你了但是还是开个issue吧（

**Comment by DeepSkyFire** [comment]
这问题我也碰到了 好烦人 有啥好办法能解决的 除了SSH里去改文件

**Comment by alexazhou** [comment]
可能是这些原因导致不能保存，可以对照排除一下，正常情况下是可以保存的，@liwanglin12是第二种情况：

* /opt/verynginx/verynginx/configs/ 权限问题

>执行 ```chmod -R 777  /opt/verynginx/verynginx/configs```

*  nginx 设置的 client body 太小

>在nginx.conf中增加一句，client_max_body_size 10m;

**Comment by liwanglin12** [comment]
看了下现在服务器定义的是
 client_max_body_size 1024m;
一直没改过，大概一直都有这么一条吧。。

**Comment by liwanglin12** [comment]
与zhou沟通后发现nginx.conf中
client_body_buffer_size 需要设置为大于config.json大小的值，遂修改为
client_body_buffer_size 64k;
问题解决。他表示太累了所以我来回这个issue了（

**Comment by alexazhou** [comment]
我写了个 trouble shooting, 以后遇到问题可以参考

 https://github.com/alexazhou/VeryNginx/wiki/Trouble-Shooting

**Comment by JoyChou93** [comment]
总结下：
client_body_buffer_size如果不配置，默认设置为8kb。
当测试10kb的post数据时，会提示`requesty body in temp file not supported`

解决办法：
增大`client_body_buffer_size`配置
或者设置client_body_buffer_size和client_max_body_size一样大，这样nginx不会存放临时文件。
