### ISSUE TITLE
做了一个最新版的docker的镜像，希望有用

### ISSUE THREAD

**Issue by halfcrazy** [alexazhou/VeryNginx#45]
https://github.com/koalagogo/verynginx_docker

**Comment by alexazhou** [comment]
多谢啦～

**Comment by alexazhou** [comment]
不知道你有兴趣开个分支合并到VeryNginx仓库里面吗？

**Comment by halfcrazy** [comment]
@alexazhou 当然，见 https://github.com/alexazhou/VeryNginx/pull/46
