### ISSUE TITLE
启用attack_sql_0的Filter情况下会导致500错误的出现

### ISSUE THREAD

**Issue by DeepSkyFire** [alexazhou/VeryNginx#47]
作者是否有即时消息联系方式，因为错误问题详情无法公开展示

**Comment by alexazhou** [comment]
Hi：
    我的微信是alexa_zhou，可以加我好友来交流。


发自网易邮箱 iPhone 版
在2016年05月21日 20:08，DeepSkyFire 写道:

作者是否有即时消息联系方式，因为错误问题详情无法公开展示

**Comment by alexazhou** [comment]
2257561 应该修复了这个问题
