### ISSUE TITLE
能不能在访问统计把ua加上

### ISSUE THREAD

**Issue by kenneth** [alexazhou/VeryNginx#5]
希望能看到ua

**Comment by alexazhou** [comment]
你说的加入UA具体是怎样呢？针对UA进行统计吗
以及是在什么场景下使用来作什么呢，能不能详细描述一下

**Comment by kenneth** [comment]
就是dashboard的统计里面，我想看到ua，不需要统计，但是要看到谁请求的。

**Comment by alexazhou** [comment]
呃，我还没明白，你想要的统计结果是统计出来哪种UA请求了网站多少次吗？

还是查看历史上哪一次请求是使用的什么UA？这种情况应该只能查access.log了
