### ISSUE TITLE
verynginx能不能安装后，直接写到服务中呢？

### ISSUE THREAD

**Issue by duanzhanling** [alexazhou/VeryNginx#50]
verynginx能不能安装后，直接写到服务中呢？
目前verynginx安装完毕后，是需要手工启动的，那么安装后，能不能直接写到/etc/init.d/下面呢

**Comment by alexazhou** [comment]
这个确实可以有。

只是编写适应不同平台的控制脚本，并测试兼容性，需要一定的工作量。我目前时间还是不够，以后可以考虑加上。

**Comment by solarhell** [comment]
Maybe we need to compatible  Systemd(systemctl) & SysV(service),and there are already some nginx sample configuration files online.

**Comment by alexazhou** [comment]
@solarhell 

I agree that . We should let the script compatible Systemd and SysV. Maybe i will do it when other work finished.

And PR welcome.
