### ISSUE TITLE
管理页面404

### ISSUE THREAD

**Issue by la0wei** [alexazhou/VeryNginx#51]
打扰了，问个很初级的问题。利用install.py安装完毕，打开管理页面的时候404。进入到nginx.conf
        location = / {
            root   html;
            index  index.html index.htm;
是因为需要修改指向的目录？

**Comment by alexazhou** [comment]
是没有正常通过 install.py 进行安装，然后文件缺失导致的。

还是通过正常方法进行安装吧

**Comment by alexazhou** [comment]
手动安装请参考 
https://github.com/alexazhou/VeryNginx/wiki/Use-own-nginx
