### ISSUE TITLE
建议在 Request Summary 中给出域名的显示

### ISSUE THREAD

**Issue by fy0** [alexazhou/VeryNginx#53]
全是uri的话根本看不清楚呀，或者加入根据域名进行筛选的选项？

PS:话说管理页面的 ABout 为什么会两个字都大写呢？笔误还是有意为之？
PS2:总体来说还是很赛艇，希望可以越来越强力

**Comment by alexazhou** [comment]
这是因为一开始设计的时候，没有考虑一个 Nginx 对应多个站点的情况，后面会进行改进

**Comment by alexazhou** [comment]
加入了一个选项来控制 summary 中的记录是否包含域名
已经合并到了 master ，下个 Release 版本中将包含这个更新
