### ISSUE TITLE
failed to get post args: requesty body in temp file not supported

### ISSUE THREAD

**Issue by galenzhao** [alexazhou/VeryNginx#54]
failed to get post args: requesty body in temp file not supported

保存配置的时候有时候会出现这个，
然后后续任何修改都没法保存了，reload之后也没法保存，
只能把nginx stop

**Comment by alexazhou** [comment]
应该是配置大到一定程度之后，Nginx 将 post 的内容存入了硬盘，导致 verynginx 后台没能获取到。

解决方法参考：#43
