### ISSUE TITLE
自己编译的nginx，怎么才能访问verynginx后台？

### ISSUE THREAD

**Issue by ladygh** [alexazhou/VeryNginx#55]
看了眼需要Included的3个文件并没有server信息

    include /opt/verynginx/verynginx/nginx_conf/in_external.conf;
    include /opt/verynginx/verynginx/nginx_conf/in_http_block.conf;
    include /opt/verynginx/verynginx/nginx_conf/in_server_block.conf;

是不是需要手动把\dashboard放到目录下然后访问？

**Comment by alexazhou** [comment]
参考：

https://github.com/alexazhou/VeryNginx/wiki/Use-own-nginx

**Comment by ladygh** [comment]
已经看了这个wiki里，里面说的还是不明确。

> 然后将 Git 仓库中的 nginx.conf 拷贝作为自己 Nginx 的配置文件。如果需要的话，可以在其中加入自己的 Nginx 配置。

看了下这个conf，实际上就是指定了一个server然后设置了root 

我现在是直接把3个include加进去了，然后把dashboard 复制到网站目录了。nginx reload后没问题。
dashboard打开没问题，登录提示Ajax request failed [status code = 404]

查了下信息似乎是点登陆的时候会post信息到 https://*/verynginx/login，但是没有这个目录啊

**Comment by alexazhou** [comment]
还是安装的问题，这里是把 lua 嵌入到 nginx 中来执行，nginx 所有的请求都会被 lua 获得。然后在这个基础上实现了一些功能，比如请求特定路径的时候，返回 dashboard 内部的文件，post 特定路径的时候，lua 直接处理并进行返回（这里是不需要配置 nginx 目录的） 

你把dashboard 复制到网站目录，然后控制面板虽然能显示出来，但是是通过 nginx 自己返回来的，并不是 lua 控制的，这个逻辑并不对，所以 post 的时候会出现 404 。

建议你可以先按照文档进行安装，在你能理解  VeryNginx 的原理之后，再修改安装方式。然后你会明白为什么要这样安装，以及问题出现在哪。

**Comment by ladygh** [comment]
收到。。用的freebsd，不太想用git安装啊。路径完全不同。。
我还是去看代码吧。不过这样写死路径的方法真的不太好啊

**Comment by ladygh** [comment]
如果有多个网站，是不是每个网站都要include一次？




________________________________

**Comment by cherishpf** [comment]
> 直接这样搞就好了
> server {
> listen 80;
> server_name waf.example.com;
> charset utf-8;
> index index.html index.htm;
> root /opt/verynginx/verynginx/dashboard;
> include /opt/verynginx/verynginx/nginx_conf/in_server_block.conf;
> }
> 
> 然后访问地址：http://waf.example.com/verynginx 就可以了，一定要加那个verynginx目录。

访问地址：http://waf.example.com/verynginx/
