### ISSUE TITLE
wiki dashboard 地址错误

### ISSUE THREAD

**Issue by wanghaibo** [alexazhou/VeryNginx#56]
The address of dashboard is http://{{your_machine_address}}/VeryNginx/index.html
应该是：
The address of dashboard is http://{{your_machine_address}}/vn/index.html

**Comment by alexazhou** [comment]
你说的应该是 Readme 吧

已经修正了，是大小写的问题，正确的地址是： http://{{your_machine_address}}/verynginx/index.html

