### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by lhuac** [alexazhou/VeryNginx#57]
:(
我在verynginx配置界面下修改了一下/verynginx路径之后报500，然后我直接删除了opt文件夹，再来安装verynginx，还是报500，之后我重新编译过nginx，之后还是报500，好神奇 :sob: 

就第一次配置verynginx成功了，修改verynginx访问路径后，怎么样也不能成功了 :(

**Comment by alexazhou** [comment]
配置存储在 /opt/verynginx/verynginx/config/ 目录下，所以如果删除了 opt 文件夹再重新安装，那么应该就不会再有影响了

如果报 500 错误的话可以看看 nginx error log 中的信息，路径是 /opt/verynginx/openresty/ngingx/logs

**Comment by lhuac** [comment]
@alexazhou 
我用的是自己编译nginx的，木有用openresty，就是第一次重新编译自己用的nginx，然后 再安装verynginx，成功了，可以访问，可我修改了访问verynginx路径之后开始报500，之后呢，再也无法安装用上了，无论是重新编译nginx再重新安装verynginx，如果include配置文件，马上500，删除又好了。感觉也不问题出在哪里了 :sob:

**Comment by alexazhou** [comment]
自己编译的 nginx 也有 error log，可以看看里面报告的什么错误，我才好帮你解决

**Comment by lhuac** [comment]
@alexazhou 
2016/07/11 19:08:56 [] 21809#0: *1 [lua] VeryNginxConfig.lua:200: update_config(): config Hash Changed:now reload config from config.json, client: 1.2.1.1, server: www.xx.com, request: "GET /verynginx/status HTTP/2.0", host: "www.xx.com", referrer: "https://www.xx.com/verynginx/index.html"

只有上面这个…就是没有相关的错误信息才……

**Comment by alexazhou** [comment]
信息有限，没办法判断问题在哪儿，推测还是安装的问题吧

先关闭 issue 了，如果有详细情况补充可以再继续回复。
