### ISSUE TITLE
启动Request Summary 后，日志出错，规则可正常使用

### ISSUE THREAD

**Issue by cypcit** [alexazhou/VeryNginx#59]
我安装成功后，功能都正常，但在congfig-》Sunnary-》Request Summary 中启动attack_sql_0统计后，在error.log出现如下错误：
2016/07/14 18:55:14 [error] 8627#0: *22 failed to run log_by_lua*: ...verynginx/verynginx/lua_script/module/request_tester.lua:111: API disabled in the context of log_by_lua*
stack traceback:
	[C]: in function 'read_body'
	...verynginx/verynginx/lua_script/module/request_tester.lua:111: in function <...verynginx/verynginx/lua_script/module/request_tester.lua:84>
	...verynginx/verynginx/lua_script/module/request_tester.lua:18: in function 'test'
	/opt/verynginx/verynginx/lua_script/module/summary.lua:52: in function 'log'
	/opt/verynginx/verynginx/lua_script/on_log.lua:5: in function </opt/verynginx/verynginx/lua_script/on_log.lua:1> while logging request, client: 10.68.31.75, server: , request: "GET /verynginx/status HTTP/1.1", host: "10.68.16.65", referrer: "http://10.68.16.65/verynginx/index.html"
导致无法统计sql攻击数据，各位大神看是什么问题？
我的全部安装脚本如下（ubuntu 14 server 64位，安装过程无报错）：
cd ~
sudo su
apt-get update
apt-get install make
ln -s /usr/bin/make  /usr/bin/gmake
apt-get install gcc
apt-get install libpcre3 libpcre3-dev
apt-get install openssl libssl-dev
apt-get install git
git clone https://github.com/alexazhou/VeryNginx.git
cd VeryNginx
python install.py install
/opt/verynginx/openresty/nginx/sbin/nginx

**Comment by alexazhou** [comment]
可能是逻辑上有些问题，我验证之后告诉你具体原因

**Comment by alexazhou** [comment]
好吧，确实有些问题，我会在这两天修正这个bug

**Comment by alexazhou** [comment]
我在 2e8a4a2 中修正了这个 bug

产生这个 bug 的原因是在 nginx 的 log 阶段，并不能获取到完整的请求数据，导致当 matcher 中包含某些条件时，即无法进行测试。。。😰

为了修正这个问题，我把 log 阶段的 matcher 匹配测试提前到了更早的阶段运行，通过 ngx.ctx 保存结果供后面使用，这样就可以了。
