### ISSUE TITLE
怎样配置VeryNginx的访问端口？

### ISSUE THREAD

**Issue by yalove** [alexazhou/VeryNginx#6]
已有域名的网站占用了80和443端口，访问VeryNginx会自动跳转到 域名加/VeryNginx/dashboard/index.html，这个页面的链接都打不开
怎样才能自定义配置VeryNginx的访问端口？
如同 server { listen：8080} 那样？

**Comment by alexazhou** [comment]
现在VeryNginx是和网站共用一套端口, 并不需要自己单独的端口
>其实暂时也无法配置单独的端口

VeryNginx控制面板的工作方式大概是这样，在请求过来的时候，对/verynginx 路径下的请求，拦截下来通过lua进行处理并返回，不走Nginx的location处理

所以你应该在现有的网站配置的http段里面加入VeryNginx的配置后，访问网站的/VeryNginx/dashboard/index.html 路径就可以了，无论是80或者433都可以
