### ISSUE TITLE
中文readme 安装后示例地址有错误

### ISSUE THREAD

**Issue by sheaven79** [alexazhou/VeryNginx#61]
VeryNginx 启动后，可以通过浏览器访问管理面板来查看状态以及进行配置。
管理面板地址为 http://{{your_machine_address}}/VeryNginx/index.html。
实际应为小写
http://{{your_machine_address}}/verynginx/index.html

**Comment by alexazhou** [comment]
已经在 51abbce 中修正，多谢你的发现
