### ISSUE TITLE
Matcher是否支持cookie、http header？

### ISSUE THREAD

**Issue by daCapricorn** [alexazhou/VeryNginx#62]
目前我们的网站在cookie里设置了一个值，用来做ab测试，将部分用户跳转到灰度环境。请问是否支持根据cookie做跳转？

**Comment by alexazhou** [comment]
目前 Matcher 还不支持通过 cookie ( http header ) 来作判断

后面我会加上

**Comment by daCapricorn** [comment]
@alexazhou 期待

**Comment by alexazhou** [comment]
至 a0e32a3 ，已经可以通过 header，cookie 来进行匹配了

**Comment by daCapricorn** [comment]
@alexazhou I will try it. thx:)
