### ISSUE TITLE
能否在Frequency Limit 达到limit的数量后，返回特定的json

### ISSUE THREAD

**Issue by si-tech** [alexazhou/VeryNginx#63]
主要是想对API做Frequency Limit 判断。如果前台ajax请求ajax超过limit，并且获取到这个特定的json后，能做相应的UI展示，比如提示用户：亲～您的操作过于频繁，请稍候再试！

**Comment by si-tech** [comment]
搞定了，看了下代码，挺好改的。

> if count_now > tonumber(count) then
    ngx.header.content_type = "application/json"
    ngx.say("{\"code\":\"888888\",\"message\":\"亲～您好快嘛人家受不鸟啦～休息一会再接着干~么么哒~\"}")
end

**Comment by kn007** [comment]
不错的需求

**Comment by bigpyer** [comment]
好浪的文案。。

**Comment by alexazhou** [comment]
这文案好叼。

看来手动配置返回内容这个功能很有必要，后面我争取加入进来

**Comment by alexazhou** [comment]
截至 bf4226b ，在 Frequency limit 和 filter 中使用自定义响应的功能已经开发完成，前后端都有了对应的支持

目前提交到了 dev 分支上，测试好之后我会合并到 master

**Comment by si-tech** [comment]
@alexazhou  给力！

**Comment by alexazhou** [comment]
已经合并到 master 啦，欢迎更新
