### ISSUE TITLE
VeryNginx支持waf类的过滤吗？

### ISSUE THREAD

**Issue by lvtao320** [alexazhou/VeryNginx#64]
SQL注入、CC攻击、恶意扫描之类的~~

**Comment by alexazhou** [comment]
VeryNginx 支持很多种 waf 类的方法，其中 Filter 模块可以根据各种规则进行过滤，Browser Verify 模块可以通过 cookies 和 javascript 对浏览器进行验证，Frequency Limit 模块可以限制特定 uri / ip 的请求频率。

你可以使用以上这些模块达到 waf 的效果。

不过 waf 并没有通用的规则，还是需要根据自己的情况，配置合适的规则，这样效果才会比较好

**Comment by alexazhou** [comment]
具体可以查看 VeryNginx 的 [文档](https://github.com/alexazhou/VeryNginx/blob/master/readme_zh.md) 和 [wiki](https://github.com/alexazhou/VeryNginx/wiki)
