### ISSUE TITLE
我没有用openresty，我用tengine，编译通过了，启动nginx的时候出现了点问题。

### ISSUE THREAD

**Issue by psychokiller666** [alexazhou/VeryNginx#65]
作者你好。

我先安装了VeryNginx`python install.py install`

tengine编译的时候 
``./configure --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-ipv6 --with-http_sysguard_module --with-http_concat_module --with-http_upstream_check_module --with-google_perftools_module --with-ld-opt='-Wl,-rpath,/opt/verynginx/openresty/luajit/lib' --add-module=/usr/local/nginx/modules/lua-nginx-module-0.10.5 --add-module=/usr/local/nginx/modules/ngx_devel_kit-0.3.0``

里面写了luajit，lua-nginx-module，ngx_devel_kit，并且也成功了，

可是service nginx start出了

``[root@iZ25qro7mxhZ ltanmp]# service nginx start
Starting nginx daemon: nginxnginx: [emerg] "set" directive is not allowed here in /opt/verynginx/verynginx/nginx_conf/in_server_block.conf:1
nginx already running.``

**Comment by alexazhou** [comment]
VeryNginx 是可以支持在 Tengine 上使用的，你的问题好像是在 nginx.conf 里面错误的地方 include 了

 **/opt/verynginx/verynginx/nginx_conf/in_server_block.conf** 

你是在哪儿里 include 这个文件的呢？可以检查下是否有错误。

**Comment by alexazhou** [comment]
正确的 include 位置可以参考 https://github.com/alexazhou/VeryNginx/wiki/Use-own-nginx

**Comment by psychokiller666** [comment]
nginx.conf里面写了

``server {
  listen       80;
  server_name  127.0.0.1;

  include /opt/verynginx/verynginx/nginx_conf/in_external.conf;
  include /opt/verynginx/verynginx/nginx_conf/in_http_block.conf;
  include /opt/verynginx/verynginx/nginx_conf/in_server_block.conf;

  location = / {
    root   html;
    index  index.html index.htm;
  }
}``

现在又出现
``[root@iZ25qro7mxhZ conf]# service nginx start
Starting nginx daemon: nginxnginx: [emerg] "upstream" directive is not allowed here in /opt/verynginx/verynginx/nginx_conf/in_http_block.conf:1
nginx already running.``

**Comment by alexazhou** [comment]
/opt/verynginx/verynginx/nginx_conf/in_external.conf;
需要在 http 块外面 include。

/opt/verynginx/verynginx/nginx_conf/in_http_block.conf; 在http块里面，server 块外面include。

/opt/verynginx/verynginx/nginx_conf/in_server_block.conf; 在 server 块里面 include





发自我的 iPhone 
在2016年08月10日 19:20，Psycho Killer 写道:

nginx.conf里面写了

``server {
listen 80;
server_name 127.0.0.1;

include /opt/verynginx/verynginx/nginx_conf/in_external.conf;
include /opt/verynginx/verynginx/nginx_conf/in_http_block.conf;
include /opt/verynginx/verynginx/nginx_conf/in_server_block.conf;

location = / {
root html;
index index.html index.htm;
}
}``

现在又出现
[root@iZ25qro7mxhZ conf]# service nginx start
Starting nginx daemon: nginxnginx: [emerg] "upstream" directive is not allowed here in /opt/verynginx/verynginx/nginx_conf/in_http_block.conf:1
nginx already running.

**Comment by psychokiller666** [comment]
按照in_external放在最外面，in_http_block放在http里面，in_server_block放在了server里面。现在出现500错误，整个verynginx文件夹设置的权限都是www:www（因为nginx和网站脚本语言之行的就是这个用户和这个用户组）。

这是demo：http://123.57.152.143/verynginx，并且lua的环境是搭建成功的http://123.57.152.143/2328/

还是没有头绪

**Comment by alexazhou** [comment]
1，既然 lua 环境已经 ok 了，可以先试试用 VeryNginx 自带的干净的 nginx.conf 来启动试试看，那里面只是配置了 VeryNginx 没有干别的，这样可以排除配置的问题。

2，当最小的 VeryNginx 可以运行之后，对比一下 VeryNginx 自带的 nginx.conf 和你目前配置文件的区别，经过修改对比就可以找到不工作的原因

**Comment by psychokiller666** [comment]
用https://github.com/alexazhou/VeryNginx/blob/master/nginx.conf 这个conf

同样是500错误

**Comment by alexazhou** [comment]
看看 /opt/verynginx/openresty/nginx/logs/error.log ，里面有出错的原因.

**Comment by psychokiller666** [comment]
'2016/08/11 15:00:04 [error] 2210#0: *1 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:00:07 [error] 2240#0: *1 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:00:17 [error] 2240#0: *2 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:00:17 [error] 2240#0: *3 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:00:17 [error] 2240#0: *4 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
[root@iZ25qro7mxhZ logs]# cat erroraa.log 
2016/08/11 15:00:04 [error] 2210#0: *1 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:00:07 [error] 2240#0: *1 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:00:17 [error] 2240#0: *2 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:00:17 [error] 2240#0: *3 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:00:17 [error] 2240#0: *4 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"
2016/08/11 15:01:03 [error] 2240#0: *6 lua entry thread aborted: runtime error: /opt/verynginx/verynginx/lua_script/module/router.lua:56: attempt to use zero-length uri
stack traceback:
coroutine 0:
        [C]: in function 'set_uri'
        /opt/verynginx/verynginx/lua_script/module/router.lua:56: in function 'filter'
        /opt/verynginx/verynginx/lua_script/on_access.lua:18: in function </opt/verynginx/verynginx/lua_script/on_access.lua:1>, client: 218.241.226.162, server: , request: "GET /verynginx HTTP/1.1", host: "hstest.ontheroadstore.com"'

**Comment by alexazhou** [comment]
1，/opt/verynginx/config/config.json 是否存在，如果存在就删除然后试试看，难道是配置损坏了。

2，如果不是以上问题，那我也猜不出来原因，只能知道是安装安装方面的问题。建议对照文档找找是否哪一步不对 

3，如果需要，今晚可以给我一个 ssh 账号，我登上去帮你排查看看

**Comment by psychokiller666** [comment]
/opt/verynginx/verynginx/configs 这里面是空的，可以提供以下ssh帐号

**Comment by alexazhou** [comment]
我的邮箱是 AlexaZhou@163.com，你有空了可以发个微信或者 QQ 号码给我，我联系你吧

**Comment by alexazhou** [comment]
目前看来很有可能是 tengine 下特有的 bug，待复现
