### ISSUE TITLE
关于summary的一些问题

### ISSUE THREAD

**Issue by kamui0523** [alexazhou/VeryNginx#66]
你好,想了解下现在summary是否是根据vhosts/sever section走的.就是每个vhosts单独统计URI.
能否支持在一个summary下支持对不同的vhosts域名筛选呢?谢谢

**Comment by javadevelopuser** [comment]
我也想知道，如果是有很多域名的话，在实时监控界面怎么看统计趋势数据呢？

**Comment by alexazhou** [comment]
summary 界面中的条目，是根据 uri 进行统计的，并不包含域名的信息。所以不同 vhost 主要是域名不同，在 summary 中并不会被反映出来，也就是多个 vhost 的结果都包含在了一起

**Comment by alexazhou** [comment]
实时监控界面一样会包含所有 vhost 汇总的统计信息

**Comment by kamui0523** [comment]
@alexazhou 
了解,那这个汇总是通过access log来获取信息的吗?

**Comment by alexazhou** [comment]
并不是通过 access log，是通过 lua 嵌入到 nginx 流中，获取执行结果，然后在 nginx 共享内存中进行统计的。
这样就算是没有打开 access log，也可以进行统计。

**Comment by kamui0523** [comment]
@alexazhou 了解,所以这些统计数据不是永久保留的是吧.根据共享内存的空间大小决定的是么.

**Comment by alexazhou** [comment]
@kamui0523 
这里有两点需要注意：

1，summary 中的统计信息在 nginx 关闭后将消失。( 但执行 nginx -s reload 重新读取配置，不会让统计信息消失  )

2，summary 中统计信息的条目受到共享内存的限制，因为 VeryNginx 在共享内存中是存储统计的结果，就是像你在图标中看到的那样，而并非存储每一条访问记录，所以统计结果占用的空间比较少。经过我实际测试，默认的共享内存大小内可以存储大概 10 k 个条目。当有更多条目时，最早的条目将会被淘汰掉而不可见。

**Comment by kamui0523** [comment]
@alexazhou 
了解,谢谢,希望后续版本可以根据域名或者vhosts来区分来源,加油!
