### ISSUE TITLE
/router.lua:55: attempt to use zero-length uri

### ISSUE THREAD

**Issue by cloudcache** [alexazhou/VeryNginx#68]
2016/08/11 07:47:45 [error] 6894#6894: *1 lua entry thread aborted: runtime error: /opt/verynginx/lua_script/module/router.lua:55: attempt to use zero-length uri
stack traceback:
coroutine 0:
	[C]: in function 'set_uri'
	/opt/verynginx/lua_script/module/router.lua:55: in function 'filter'
	/opt/verynginx/lua_script/on_access.lua:15: in function </opt/verynginx/lua_script/on_access.lua:1>, client: 183.157.65.58, server: localhost, request: "GET /verynginx HTTP/1.1", host: "112.17.32.38"
2016/08/11 07:51:23 [error] 6905#6905: *9363 lua entry thread aborted: runtime error: /opt/verynginx/lua_script/module/router.lua:55: attempt to use zero-length uri
stack traceback:
coroutine 0:
	[C]: in function 'set_uri'
	/opt/verynginx/lua_script/module/router.lua:55: in function 'filter'
	/opt/verynginx/lua_script/on_access.lua:15: in function </opt/verynginx/lua_script/on_access.lua:1>, client: 183.157.65.58, server: localhost, request: "GET /verynginx HTTP/1.1", host: "112.17.32.38"
2016/08/11 07:51:26 [error] 6893#6893: *18725 lua entry thread aborted: runtime error: /opt/verynginx/lua_script/module/router.lua:55: attempt to use zero-length uri
stack traceback:
coroutine 0:
	[C]: in function 'set_uri'
	/opt/verynginx/lua_script/module/router.lua:55: in function 'filter'
	/opt/verynginx/lua_script/on_access.lua:15: in function </opt/verynginx/lua_script/on_access.lua:1>, client: 183.157.65.58, server: localhost, request: "GET /verynginx HTTP/1.1", host: "112.17.32.38"
2016/08/11 07:51:27 [error] 6898#6898: *18771 lua entry thread aborted: runtime error: /opt/verynginx/lua_script/module/router.lua:55: attempt to use zero-length uri
stack traceback:
coroutine 0:
	[C]: in function 'set_uri'
	/opt/verynginx/lua_script/module/router.lua:55: in function 'filter'
	/opt/verynginx/lua_script/on_access.lua:15: in function </opt/verynginx/lua_script/on_access.lua:1>, client: 183.157.65.58, server: localhost, request: "GET /verynginx HTTP/1.1", host: "112.17.32.38"

**Comment by psychokiller666** [comment]
我也遇到了和你一样的问题

https://github.com/alexazhou/VeryNginx/issues/65

**Comment by alexazhou** [comment]
@cloudcache  

你的 Nginx 也是 tengine 吗？以及你是怎么安装的呢？

**Comment by cloudcache** [comment]
直接git回来然后运行安装脚本和替换成tengine 都遇到这个问题；服务器是ubuntu

**Comment by alexazhou** [comment]
我平时使用  Fedora 开发。我晚点找个 ubuntu 的环境试试看能不能复现，你出 bug 的系统版本号码是多少呢？

**Comment by alexazhou** [comment]
在干净的 ubuntu 14.04.3 LTS 上，通过脚本安装没有能复线这个 bug

有空我会试试 Tengine
