### ISSUE TITLE
nginx配置不能保存，已参照wiki上的方法配置

### ISSUE THREAD

**Issue by GavinLjr** [alexazhou/VeryNginx#69]
已参照一下配置，nginx的proxy pass配置还是无法保存
1, nginx 进程对 /opt/verynginx/verynginx/configs/ 无写权限

执行 chmod -R 777 /opt/verynginx/verynginx/configs
2, nginx 设置的 client body 太小，导致请求体被缓存到文件，导致 lua 代码没有获取到请求体。

在nginx.conf中增加一句，client_body_buffer_size 128k;

**Comment by GavinLjr** [comment]
我的错，把Proxy Host当转发连接了

**Comment by alexazhou** [comment]
可能文档还是不够健全，后续我会把典型的应用，写成配置实例，方便大家参考。
