### ISSUE TITLE
页面刷新就退出了

### ISSUE THREAD

**Issue by 0312birdzhang** [alexazhou/VeryNginx#72]
看代码里面有设置cookie，刷新之后没判断

**Comment by alexazhou** [comment]
前端控制面板是个单页面应用，目前每次载入都会重新初始化面板。因为并没有对之前的 cookies 进行判断处理，所以会这样。后面我会加上这里的判断处理，使得在登录 cookies 有效期内就不需要重新登录了

**Comment by 0312birdzhang** [comment]
嗯，正在研究大神的代码 :smile

**Comment by alexazhou** [comment]
已经改进，目前代码已经合并到 master，下个 Release 版本中就会包含这个改进😄

**Comment by 0312birdzhang** [comment]
赞 :+1:
