### ISSUE TITLE
可以添加server_name吗？

### ISSUE THREAD

**Issue by 0312birdzhang** [alexazhou/VeryNginx#73]
现在backend只能动态设置upstream跟proxy_pass，对于多个server_name没有设置的地方，就是vhost的功能。
也可能我理解的不对，verynginx的思想跟vhost不一样吧

**Comment by alexazhou** [comment]
是说怎样通过不同的 server_name 来转发请求到不同的后端吗？

在 Nginx 中，server_name 用来匹配请求，而请求匹配的功能在 VN 中是通过 Matcher 来实现的，这样的好处是不光可以通过 server_name ，还可以通过其他很多条件来匹配。

所以对上面的需求来说，只需要定义不同的  matcher 来匹配不同的 **host** , 就可以达到 server_name 的目的了

**Comment by 0312birdzhang** [comment]
多个server_name 来转发到一个后端的话在配置上有些繁琐了 :sweat_smile:

**Comment by alexazhou** [comment]
😅确实是个问题，目前 Matcher 中不太方便对多个 server_name 进行匹配，这个已经在开发计划中了
目前如果想匹配多个域名，可以考虑使用正则表达式的方式

**Comment by 0312birdzhang** [comment]
嗯，目前只能用正则了，3Q
