### ISSUE TITLE
failed to run balancer_by_lua*

### ISSUE THREAD

**Issue by Zard1991** [alexazhou/VeryNginx#74]
hi alexazhou:
添加upstream后出现该问题:
module 'ngx.balancer' not found!
我已经安装了lua-nginx-module-master,可以正常启动。谢谢

**Comment by alexazhou** [comment]
安装方式，以及所用的配置是怎的呢？

也可以参考看是否有对应的解决方案：https://github.com/alexazhou/VeryNginx/wiki/Trouble-Shooting

**Comment by Zard1991** [comment]
使用nginx手动添加模块进行编译安装的，原因正在确认中，目前怀疑是模块安装出错。
使用openrestry安装后未出现问题。再次感谢您对问题的及时反馈。

**Comment by alexazhou** [comment]
客气啦，可能是 balance 是openresty 比较新的特性，所以单独的 lua 模块没有能集成进来，我有时间的时候会去确认一下这个


发自网易邮箱 iPhone 版
在2016年08月19日 14:08，Zard1991 写道:

使用nginx手动添加模块进行编译安装的，原因正在确认中，目前怀疑是模块安装出错。
使用openrestry安装后未出现问题。再次感谢您对问题的及时反馈。

**Comment by jim3ma** [comment]
@alexazhou 手动添加模块安装的错误，现在解决了么？同样的问题哦。能否把这个issue重新open一下呢，

**Comment by jim3ma** [comment]
@Zard1991 root cause 发现了，可以解决了哦！ #108
