### ISSUE TITLE
Error happend when i use TLS with VeryNginx

### ISSUE THREAD

**Issue by solarhell** [alexazhou/VeryNginx#8]
https://api.solarhell.com/VeryNginx/dashboard/index.html
I want to use TLS with it.I have already changed the http resources to https,but when i type verynginx to login,the screen just didn't change.
I hope you can fix it.Thanks.
![1](https://cloud.githubusercontent.com/assets/10279583/12841080/c558b6f4-cc23-11e5-929c-2577c8b32fbd.png)

**Comment by alexazhou** [comment]
Thank you for the report. 
I'm on the way to wuhan，i will test this case after arrived.

**Comment by alexazhou** [comment]
I tried to login the verynginx on your website, and i see the AJAX request response false, that means the username:password pair was incorrect generally. 

Do you have changed the password ever?  

If you changed
> there is a config.json in /opt/VeryNginx/VeryNginx/, the file contain the all verynginx config, you can find password in it.

if you not changed
>Does verynginx working in http scheme?

**Comment by solarhell** [comment]
Yes,now it works well in both http & https scheme.It's my mistake that i forgot to change one js file to the Protocol-relative URL.
I will make a pull request to provide an option to turn off the vue.js's development mode and change all static files to the Protocol-relative URL.

**Comment by alexazhou** [comment]
Good, you are so nice! 
I think i forget to use the Protocol-relative URL, so VeryNginx not work in https scheme. 
Hope you can fix that.
