### ISSUE TITLE
为什么没有verynginx的官方网站？

### ISSUE THREAD

**Issue by wuxiangege** [alexazhou/VeryNginx#80]
<p>作者你好，我在谷歌上找了一圈，都没见到verynginx的官方网站，只有github上的一个项目。赶快建一个网站出来啊，像春哥一样。春哥那openresty整得风水起的，网站看得也专业，推广也快。</p>

**Comment by alexazhou** [comment]
很好的建议。

等忙完了这阵，是时候做一个官方网站啦
