### ISSUE TITLE
怎么升级 openresty？

### ISSUE THREAD

**Issue by cielpy** [alexazhou/VeryNginx#81]
python install.py update 命令只能升级 verynginx

**Comment by alexazhou** [comment]
执行
```
python install.py update openresty
```
即可😄

**Comment by cielpy** [comment]
![image](https://cloud.githubusercontent.com/assets/3138493/18075403/0ccb25aa-6ea7-11e6-8ef7-23a38ef7d288.png)

提示 update 只能更新 verynginx :(

**Comment by alexazhou** [comment]
So sad. 
那就是我还没有做出来这个功能😅

目前的办法是先备份原来的配置，然后重新安装，安装好之后再把文件覆盖回去
```
/opt/verynginx/verynginx/configs/config.json
```

这样就可以升级到新的 openresty 了

ps:
如果修改过 nginx 配置的话，还需要备份 
```
/opt/verynginx/openresry/nginx/conf/nginx.conf
```

**Comment by cielpy** [comment]
好吧，其实我昨天用 python install.py install openresty 升级了，nginx.conf 配置好像没丢。。。

**Comment by alexazhou** [comment]
嗯，我刚看了一下代码，通过

```
python install.py install openresty 
```

来升级 openresty ，其实是调用了 openresty 自己的 make install，是不会丢失 nginx.conf 配置的

就是install.py 的命令行不太对，缺少了升级的命令，我回头来把他给修复了

**Comment by cielpy** [comment]
@alexazhou 升级命令这个是不是已经修改了？可以关了？
