### ISSUE TITLE
请问rewrite_by_lua_file写在http块里面和写在location里面的区别

### ISSUE THREAD

**Issue by MrTonyDu** [alexazhou/VeryNginx#83]
https://github.com/openresty/lua-nginx-module的rewrite_by_lua_file是写在location里面的，写在http块里面的话和location是怎样的一种关系呢

**Comment by alexazhou** [comment]
写在 http 块里面，会对所有的请求都生效，并不区分 location 


Sent from my iPhone.
在2016年09月01日 16:25，MrTonyDu 写道:

https://github.com/openresty/lua-nginx-module的rewrite_by_lua_file是写在location里面的，写在http块里面的话和location是怎样的一种关系呢
