### ISSUE TITLE
关于获取host

### ISSUE THREAD

**Issue by MrTonyDu** [alexazhou/VeryNginx#84]
local hostname = ngx.var.http_host or ngx.var.host
我发现ngx.var.host获取的主机是没有端口的，而ngx.var.http_host获取的是有端口的，我需要有端口的host，ngx.var.http_host是总不为nil的吗？

**Comment by alexazhou** [comment]
能不能具体说明一下，你是想实现什么功能呢？

在端口为80的情况下，ngx.var.http_host 和 ngx.var.host 是一样的值，端口不为80的情况下，ngx.var.http_host 包含端口信息，而 ngx.var.host 不包含

**Comment by MrTonyDu** [comment]
我把wordpress的rewrite写到vn中了，但是这会影响我的主机管理面板访问，所以我想对wordpress的rewrite的matcher添加带端口的host条件

**Comment by alexazhou** [comment]
噢，现在 Matcher 中的 host 信息使用的是 ngx.var.host 进行匹配的，所以还不能在 Matcher 中匹配 host 的端口信息😱...

后续会加入端口的匹配

**Comment by MrTonyDu** [comment]
嗯，thanks
