### ISSUE TITLE
控制面板 PorxyPass 无法选择 已经添加的 Up Stream

### ISSUE THREAD

**Issue by zhang5171291** [alexazhou/VeryNginx#88]
控制面板 PorxyPass 无法选择 已经添加的 Up Stream

![image](https://cloud.githubusercontent.com/assets/495785/18655054/3938a67c-7f18-11e6-9379-b2270ec43de8.png)

**Comment by xvipservice** [comment]
遇到同样的问题

**Comment by alexazhou** [comment]
多谢反馈。
之前重构前端代码的时候，不小心将一个地方改坏了，汗，而 CI 系统又没有覆盖前端，所以没有检查出来

我已经在 #2762bec 中修正了
