### ISSUE TITLE
配置管理的一些问题

### ISSUE THREAD

**Issue by yangdongxiang** [alexazhou/VeryNginx#89]
首先感谢作者的辛苦coding，写了一个很不错的项目。
在使用过程中有以下问题：
1. 我在config-general 中配置HostLimit 中填写了我的主机地址后（指访问verynginx的客户端电脑IP），nginx会返回404.

2. 因为一般如果用在线上，nginx都是多台部署，这样的话我就需要在每台openresty上部署verynginx，如果我要建立规则，那就需要在每台verynginx上去部署，这样配置管理很不方便，是不是可以考虑加入zookeeper 这样的统一配置管理？或者其他的。。

再次感谢作者

**Comment by alexazhou** [comment]
客气了，也多谢你的关注:-)。


1，VN 中提供了选项来配置一个域名作为 Host Limit，配置之后就只能从那个域名访问控制面板，通过其他域名访问就会是 404。这个选项并不是用来限制访问者的 IP，如果要限制来源 IP ，配置一条 filter 规则即可😄。


2，统一配置管理一直想做，只是最近被太多事情缠住一直没能抽出时间，具体通过什么方式配置也在考虑。我对 zookeeper 并不了解，我会去了解一下。目前如果要进行配置同步，有种变通的方法是在一台机器上面讲 VN 配置好之后，将 config.json 文件分发到其他机器上，然后重启其他机器的 VN，这样配置就全部同步了


Sent from my iPhone.
在2016年09月21日 17:25，yangdongxiang 写道:

首先感谢作者的辛苦coding，写了一个很不错的项目。
在使用过程中有以下问题：
1. 我在config-general 中配置HostLimit 中填写了我的主机地址后（指访问verynginx的客户端电脑IP），nginx会返回404.

因为一般如果用在线上，nginx都是多台部署，这样的话我就需要在每台openresty上部署verynginx，如果我要建立规则，那就需要在每台verynginx上去部署，这样配置管理很不方便，是不是可以考虑加入zookeeper 这样的统一配置管理？或者其他的。。

再次感谢作者

**Comment by yangdongxiang** [comment]
感谢您百忙之中的回复。
还有其他问题想请教一下
 我在设置请求频率限制模块当中配置了一个matcher，在action当中设置每秒请求100次，达到这个条件返回429状态码，确实返回了429，但是openresty也会返回500的状态码。。

**Comment by alexazhou** [comment]
请问 “openresty也会返回500的状态码” 具体是怎样的情况呢，可否详细描述一下？
正常情况下不应该出现 500 的状态码（除非是配置为返回 500）








在 2016-09-22 15:00:17，"yangdongxiang" <notifications@github.com> 写道：


感谢您百忙之中的回复。
还有其他问题想请教一下
我在设置请求频率限制模块当中配置了一个matcher，在action当中设置每秒请求100次，达到这个条件返回429状态码，确实返回了429，但是openresty也会返回500的状态码。。

**Comment by yangdongxiang** [comment]
具体配置是这样的
我在matcher 里面配置了一个	Condition 条件为HOST=XXX.XXX.com
在Customer Action 里面配置Frequency Limit ,设置这个Matcher 为1s,100次，定义状态码为429,但是我设置过后，在测试的时候会得到500的状态码

**Comment by alexazhou** [comment]
我刚才试了，没有能重现 500 的错误，可否将你的 error.log 中的内容贴一些上来，路径是 

**/opt/verynginx/openresty/nginx/logs/error.log** 

那里会包含 500 的报错信息，这样可以可以排查其中的问题

**Comment by yangdongxiang** [comment]
error.log 我看过了，没有异常日志，500的错误状态响应是在我虚拟主机日志里面的，例如，api.xxx.com.access.log里面打印出来的，但是如果我把规则去掉，500的错误状态就立马没有了。。

**Comment by yangdongxiang** [comment]
我没有python install.py install 安装openresty 和verynginx，因为我在安装verynginx的时候openresty就已经安装好了，所以我是python install.py install verynginx安装的，然后我在global,http,server三个配置块里面分布include了三个verynginx的配置文件。

**Comment by alexazhou** [comment]
这样安装应该没问题

我今天早上突然想到，没有 error.log 是否是由于没有在 nginx.conf 中开启 error.log 选项？正常情况下 error.log 中应该会有关于错误的信息。 可以先查一下 nginx.conf 中关于 error.log 的配置，这样得到了 log 之后，就可以知道 500 的问题是什么

**Comment by yangdongxiang** [comment]
openresty的配置里面我打开了error.log的配置选项，但是只打印crit级别的错误日志，不知道是不是跟这个有关系。
因为我nginx配置错误导致的错误都会被打印出来，但是vn在抛500的时候，nginx的error.log确实没有关于500的错误日志。

**Comment by alexazhou** [comment]
很大可能跟日志级别有关系，建议先去掉 crit 级别的限制（默认情况下会输出全部的错误日志）

只要有了日志，我可以“复现”这个情况，一般来说问题都可以解决的
