### ISSUE TITLE
基础架构是nginx，而不是openresty，我可以通过加载nginx第三方模块，来部署verynginx吗？

### ISSUE THREAD

**Issue by orright** [alexazhou/VeryNginx#90]
非常喜欢verynginx，做的非常棒！

**Comment by alexazhou** [comment]
完全可以的，只是需要手工进行部署，我写了个文档，你可以参考：

https://github.com/alexazhou/VeryNginx/wiki/Use-own-nginx

**Comment by orright** [comment]
感谢作者
