### ISSUE TITLE
拦截日志是否记录?

### ISSUE THREAD

**Issue by Canon88** [alexazhou/VeryNginx#94]
你好.我已经安装了verynginx.并手动触发了SQL注入的规则.
请问verynginx是否会记录拦截动作 用户源IP 等信息.谢谢.

**Comment by alexazhou** [comment]
并没有单独记录拦截的信息，如果需要知道是哪些请求被拦截了，需要到 Nginx access.log 中查看

**Comment by Canon88** [comment]
好的谢谢您.



115664000@qq.com
 
发件人： AlexaZhou
发送时间： 2016-11-01 14:28
收件人： alexazhou/VeryNginx
抄送： Canon88; Author
主题： Re: [alexazhou/VeryNginx] 拦截日志是否记录? (#94)
并没有单独记录拦截的信息，如果需要知道是哪些请求被拦截了，需要到 Nginx access.log 中查看
