### ISSUE TITLE
VeryNginx online demo 无法使用

### ISSUE THREAD

**Issue by sy-yanghuan** [alexazhou/VeryNginx#96]
使用chrome 无法正确登陆，点击登陆无反应，存在以下错误
![qq 20161109173507](https://cloud.githubusercontent.com/assets/2771349/20133531/e0f78106-a6a2-11e6-9fec-0ac84a27189d.png)

**Comment by alexazhou** [comment]
刚我自己测试是可以的。我看到图中好几个  not defined，可以检查一下看看是否有资源没有加载成功

**Comment by sy-yanghuan** [comment]
好的，我在调试看下，多谢~

发自我的 iPhone
